src/objects/MetadataDeployment__e.object
<CustomObject>
    <fields>
        <fullName>DeploymentId__c</fullName>
        <label>DeploymentId</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>MetadataDeployment</label>
    <pluralLabel>Metadata Deployment</pluralLabel>
</CustomObject>

src/objects/WidgetPreset__mdt.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DefaultNotification__c</fullName>
        <label>Default Notification</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Widget Present</label>
    <pluralLabel>Widget Presents</pluralLabel>
</CustomObject>

src/classes/CustomMetadataDemoController.cls
public with sharing class CustomMetadataDemoController {
    
    public WidgetPreset__mdt Record {get;set;}
    
    public String DeployId {get;set;}    
    
    public String DeployResult {get;set;}
    
    public PageReference init() {
        
        Record = [select DeveloperName, Label, DefaultNotification__c, Alias__c 
                    from WidgetPreset__mdt
                    where DeveloperName = 'BluetoohToothbrush'];
                    
        return null;
    }
    
    public PageReference save() {
                        
        DeployId = 
            CustomMetadata.Operations
                .callback(
                    MetadataDeployment__e.getSObjectType(),
                    MetadataDeployment__e.DeploymentId__c, 
                    MetadataDeployment__e.Result__c)
                .enqueueUpsertRecords(
                    new List<SObject> { Record })
                .deployId;
                        
        return null;
    }
    
    public PageReference saveHandler() {

        DeployId = null;                
        CustomMetadata.SaveRecordResult result = 
            (CustomMetadata.SaveRecordResult) 
                JSON.deserialize(DeployResult, CustomMetadata.SaveRecordResult.class);
        if(!result.success) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, result.message));            
        }            
        
        return null;
    }
}